"use client";
import React, { useEffect, useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";
import { ThemeProvider } from "@/components/Theme";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "My Blog APP",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
 
  const [themeMode, setThememode] = useState('light');
  
  const lightTheme = () => {
    setThememode("light");
  };
  const darkTheme = () => {
    setThememode("dark");
  };
  
  useEffect(() => {
    const htmlElement = document.querySelector("html");
    if (htmlElement) {
      htmlElement.classList.remove("light", "dark");
      htmlElement.classList.add(themeMode);
    }
  }, [themeMode]);
  return (
    <>
      <ThemeProvider value={{themeMode,lightTheme,darkTheme}}>
        <html lang="en">
          <body className={inter.className}>
            {pathname !== "/signup" && pathname !== "/" && <Navbar />}

            {children}
          </body>
        </html>
      </ThemeProvider>
    </>
  );
}
